# Generated by Django 4.1.5 on 2023-01-30 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(max_length=20)),
                ('allergy', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=50)),
                ('bloodgroup', models.CharField(max_length=5, null=True)),
                ('nextofkin', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pastcomplaint', models.CharField(max_length=100, null=True)),
                ('presentcomplaint', models.CharField(max_length=100, null=True)),
                ('recommendation', models.CharField(max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caremax.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentname', models.CharField(max_length=50, null=True)),
                ('doze', models.TextField(max_length=200, null=True)),
                ('comment', models.TextField(max_length=200, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caremax.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=50, null=True)),
                ('testresults', models.CharField(max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caremax.patient')),
            ],
        ),
    ]
