# Generated by Django 4.1.5 on 2023-01-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caremax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bloodgroup',
        ),
    ]
