# Generated by Django 4.1.5 on 2023-01-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caremax', '0002_remove_patient_bloodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
