# Generated by Django 4.1.5 on 2023-02-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caremax', '0003_patient_bloodgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bloodgroup',
        ),
    ]
