# Generated by Django 4.1.5 on 2023-02-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caremax', '0005_patient_bloodgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
