# Generated by Django 4.1.5 on 2023-02-13 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caremax', '0006_rename_patient_test_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_tests', to='caremax.patient'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_treatment', to='caremax.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_visits', to='caremax.patient'),
        ),
    ]
