# Generated by Django 4.1.5 on 2023-02-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caremax', '0008_inventory_remove_patient_bloodgroup_patient_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='comment',
            new_name='remarks',
        ),
    ]
