# Generated by Django 4.1.5 on 2023-02-24 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caremax', '0009_rename_comment_treatment_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_treatments', to='caremax.patient'),
        ),
    ]
