# Generated by Django 4.1.5 on 2023-03-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caremax', '0010_alter_treatment_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='amount_dispensed',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='amount_received',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='balance',
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Cleaning', 'Cleaning'), ('Medicine', 'Medicine'), ('IT Equipment', 'IT Equipment')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='export_to_csv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='issued_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='received_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='rate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7, null=True),
        ),
    ]
