# Generated by Django 4.1.5 on 2023-04-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caremax', '0013_alter_inventory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
