# Generated by Django 4.1.5 on 2023-04-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caremax', '0014_remove_inventory_category_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('rate', models.IntegerField(default=0, null=True)),
                ('quantity_received', models.IntegerField(default=0)),
                ('received_by', models.CharField(max_length=100, null=True)),
                ('issued_by', models.CharField(max_length=100, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('export_to_csv', models.BooleanField(default=True)),
                ('stockcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_inventory', to='caremax.stockcategory')),
            ],
        ),
    ]
