# Generated by Django 4.1.5 on 2023-04-24 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caremax', '0015_stockcategory_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='issued_to',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stockcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caremax.stockcategory'),
        ),
    ]
