# Generated by Django 4.1.5 on 2023-04-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caremax', '0016_stock_issued_to_alter_stock_stockcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='issued_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
