# Generated by Django 4.1.5 on 2023-05-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caremax', '0017_stock_issued_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
